#!/bin/bash
# Fuzzy find directories and open one in a tmux session

dir=$(find ~/Desktop ~/dev ~/Documents ~/dotfiles -maxdepth 5  -type d | fzf )

if [[ $dir ]]; then
    cd $dir
    baseName=$(basename $dir)
    if [[ -z "${TMUX}" ]]; then
        tmux new -A -s $baseName
    else
        tmux new -A -s $baseName -d
    fi
fi
